/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as ApiPublicPhotoSplatRouteImport } from './routes/api/public/photo.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const ApiPublicPhotoSplatRoute = ApiPublicPhotoSplatRouteImport.update({
  id: '/api/public/photo/$',
  path: '/api/public/photo/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/api/public/photo/$': typeof ApiPublicPhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin'
    | '/portfolio/$category'
    | '/portfolio/'
    | '/api/public/photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin'
    | '/portfolio/$category'
    | '/portfolio'
    | '/api/public/photo/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/_authenticated/admin'
    | '/portfolio/$category'
    | '/portfolio/'
    | '/api/public/photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  ApiPublicPhotoSplatRoute: typeof ApiPublicPhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/api/public/photo/$': {
      id: '/api/public/photo/$'
      path: '/api/public/photo/$'
      fullPath: '/api/public/photo/$'
      preLoaderRoute: typeof ApiPublicPhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  ApiPublicPhotoSplatRoute: ApiPublicPhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
