/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BookRouteImport } from './routes/book'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DuoRouteImport } from './routes/duo'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as JournalIndexRouteImport } from './routes/journal.index'
import { Route as JournalSlugRouteImport } from './routes/journal.$slug'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio.index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio.$category'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAdvancedRouteImport } from './routes/_authenticated/admin.advanced'
import { Route as AuthenticatedAdminCategoriesRouteImport } from './routes/_authenticated/admin.categories'
import { Route as AuthenticatedAdminInquiriesRouteImport } from './routes/_authenticated/admin.inquiries'
import { Route as AuthenticatedAdminPagesRouteImport } from './routes/_authenticated/admin.pages'
import { Route as AuthenticatedAdminPhotosRouteImport } from './routes/_authenticated/admin.photos'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminSubscribersRouteImport } from './routes/_authenticated/admin.subscribers'
import { Route as AuthenticatedAdminTestimonialsRouteImport } from './routes/_authenticated/admin.testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DuoRoute = DuoRouteImport.update({
  id: '/duo',
  path: '/duo',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => PortfolioRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdvancedRoute =
  AuthenticatedAdminAdvancedRouteImport.update({
    id: '/advanced',
    path: '/advanced',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriesRoute =
  AuthenticatedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInquiriesRoute =
  AuthenticatedAdminInquiriesRouteImport.update({
    id: '/inquiries',
    path: '/inquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPagesRoute = AuthenticatedAdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPhotosRoute =
  AuthenticatedAdminPhotosRouteImport.update({
    id: '/photos',
    path: '/photos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscribersRoute =
  AuthenticatedAdminSubscribersRouteImport.update({
    id: '/subscribers',
    path: '/subscribers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTestimonialsRoute =
  AuthenticatedAdminTestimonialsRouteImport.update({
    id: '/testimonials',
    path: '/testimonials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/duo': typeof DuoRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/admin/advanced': typeof AuthenticatedAdminAdvancedRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/duo': typeof DuoRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/journal': typeof JournalIndexRoute
  '/portfolio': typeof PortfolioIndexRoute
  '/admin/advanced': typeof AuthenticatedAdminAdvancedRoute
  '/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/duo': typeof DuoRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/journal/$slug': typeof JournalSlugRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/journal/': typeof JournalIndexRoute
  '/portfolio/': typeof PortfolioIndexRoute
  '/_authenticated/admin/advanced': typeof AuthenticatedAdminAdvancedRoute
  '/_authenticated/admin/categories': typeof AuthenticatedAdminCategoriesRoute
  '/_authenticated/admin/inquiries': typeof AuthenticatedAdminInquiriesRoute
  '/_authenticated/admin/pages': typeof AuthenticatedAdminPagesRoute
  '/_authenticated/admin/photos': typeof AuthenticatedAdminPhotosRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscribers': typeof AuthenticatedAdminSubscribersRoute
  '/_authenticated/admin/testimonials': typeof AuthenticatedAdminTestimonialsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/duo'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/admin'
    | '/journal/$slug'
    | '/portfolio/$category'
    | '/journal/'
    | '/portfolio/'
    | '/admin/advanced'
    | '/admin/categories'
    | '/admin/inquiries'
    | '/admin/pages'
    | '/admin/photos'
    | '/admin/posts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/duo'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/journal/$slug'
    | '/portfolio/$category'
    | '/journal'
    | '/portfolio'
    | '/admin/advanced'
    | '/admin/categories'
    | '/admin/inquiries'
    | '/admin/pages'
    | '/admin/photos'
    | '/admin/posts'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/subscribers'
    | '/admin/testimonials'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/book'
    | '/contact'
    | '/duo'
    | '/portfolio'
    | '/privacy'
    | '/services'
    | '/terms'
    | '/_authenticated/admin'
    | '/journal/$slug'
    | '/portfolio/$category'
    | '/journal/'
    | '/portfolio/'
    | '/_authenticated/admin/advanced'
    | '/_authenticated/admin/categories'
    | '/_authenticated/admin/inquiries'
    | '/_authenticated/admin/pages'
    | '/_authenticated/admin/photos'
    | '/_authenticated/admin/posts'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscribers'
    | '/_authenticated/admin/testimonials'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  DuoRoute: typeof DuoRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  TermsRoute: typeof TermsRoute
  JournalSlugRoute: typeof JournalSlugRoute
  JournalIndexRoute: typeof JournalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duo': {
      id: '/duo'
      path: '/duo'
      fullPath: '/duo'
      preLoaderRoute: typeof DuoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/advanced': {
      id: '/_authenticated/admin/advanced'
      path: '/advanced'
      fullPath: '/admin/advanced'
      preLoaderRoute: typeof AuthenticatedAdminAdvancedRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categories': {
      id: '/_authenticated/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inquiries': {
      id: '/_authenticated/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AuthenticatedAdminInquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pages': {
      id: '/_authenticated/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AuthenticatedAdminPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/photos': {
      id: '/_authenticated/admin/photos'
      path: '/photos'
      fullPath: '/admin/photos'
      preLoaderRoute: typeof AuthenticatedAdminPhotosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscribers': {
      id: '/_authenticated/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AuthenticatedAdminSubscribersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/testimonials': {
      id: '/_authenticated/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AuthenticatedAdminTestimonialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdvancedRoute: typeof AuthenticatedAdminAdvancedRoute
  AuthenticatedAdminCategoriesRoute: typeof AuthenticatedAdminCategoriesRoute
  AuthenticatedAdminInquiriesRoute: typeof AuthenticatedAdminInquiriesRoute
  AuthenticatedAdminPagesRoute: typeof AuthenticatedAdminPagesRoute
  AuthenticatedAdminPhotosRoute: typeof AuthenticatedAdminPhotosRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscribersRoute: typeof AuthenticatedAdminSubscribersRoute
  AuthenticatedAdminTestimonialsRoute: typeof AuthenticatedAdminTestimonialsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdvancedRoute: AuthenticatedAdminAdvancedRoute,
  AuthenticatedAdminCategoriesRoute: AuthenticatedAdminCategoriesRoute,
  AuthenticatedAdminInquiriesRoute: AuthenticatedAdminInquiriesRoute,
  AuthenticatedAdminPagesRoute: AuthenticatedAdminPagesRoute,
  AuthenticatedAdminPhotosRoute: AuthenticatedAdminPhotosRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscribersRoute: AuthenticatedAdminSubscribersRoute,
  AuthenticatedAdminTestimonialsRoute: AuthenticatedAdminTestimonialsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PortfolioRouteChildren {
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioCategoryRoute: PortfolioCategoryRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  DuoRoute: DuoRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  TermsRoute: TermsRoute,
  JournalSlugRoute: JournalSlugRoute,
  JournalIndexRoute: JournalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
